# Generated by Django 4.2.16 on 2026-02-25 22:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendors", "0007_discount_ar_badge_text_discount_delivery_radius_m_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorReel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "s3_key",
                    models.CharField(
                        help_text="S3 object key for the reel video file.",
                        max_length=500,
                    ),
                ),
                (
                    "thumbnail_s3_key",
                    models.CharField(
                        blank=True,
                        help_text="S3 object key for the reel thumbnail image.",
                        max_length=500,
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(help_text="Video duration in seconds."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Processing"),
                            ("ACTIVE", "Active"),
                            ("REJECTED", "Rejected"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="PROCESSING",
                        max_length=12,
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("completion_count", models.PositiveIntegerField(default=0)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Vendor-controlled display order. Lower = shown first.",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "moderation_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes on moderation decision."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reels",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Reel",
                "verbose_name_plural": "Vendor Reels",
                "ordering": ["display_order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["vendor", "is_active"], name="reel_vendor_active_idx"
                    ),
                    models.Index(
                        fields=["moderation_status", "is_active"],
                        name="reel_moderation_active_idx",
                    ),
                ],
            },
        ),
    ]
