# Generated by Django 4.2.7 on 2026-02-28 12:00

import django.db.models.deletion
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('guest_token', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('preferred_radius_m', models.IntegerField(default=500)),
                ('preferred_categories', models.JSONField(blank=True, default=list)),
                ('last_known_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_known_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('behavioral_data', models.JSONField(blank=True, default=dict)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('data_export_requested_at', models.DateTimeField(blank=True, null=True)),
                ('consent_records', models.JSONField(blank=True, default=list)),
                ('social_auth_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('social_auth_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='auth.user')),
            ],
            options={
                'db_table': 'customer_users',
                'indexes': [
                    models.Index(fields=['guest_token'], name='customer_auth_customer_user_guest_token_idx'),
                    models.Index(fields=['is_deleted', 'created_at'], name='customer_auth_customer_user_deleted_created_idx'),
                    models.Index(fields=['last_known_lat', 'last_known_lng'], name='customer_auth_customer_user_location_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('LOCATION', 'Location Services'), ('ANALYTICS', 'Analytics Tracking'), ('MARKETING', 'Marketing Communications'), ('TERMS', 'Terms of Service'), ('PRIVACY', 'Privacy Policy'), ('VOICE', 'Voice Data Processing')], db_index=True, max_length=20)),
                ('consented', models.BooleanField(db_index=True)),
                ('consent_version', models.CharField(default='1.0', max_length=10)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('consented_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('guest_token', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_auth.customeruser')),
            ],
            options={
                'db_table': 'consent_records',
                'indexes': [
                    models.Index(fields=['user', 'consent_type', 'consented_at'], name='customer_auth_consent_user_type_date_idx'),
                    models.Index(fields=['guest_token', 'consent_type'], name='customer_auth_consent_guest_type_idx'),
                    models.Index(fields=['consented_at', 'consent_type'], name='customer_auth_consent_date_type_idx'),
                ],
                'unique_together': {('user', 'consent_type', 'consented_at'), ('guest_token', 'consent_type', 'consented_at')},
            },
        ),
        migrations.CreateModel(
            name='GuestToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('api_calls_count', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'guest_tokens',
                'indexes': [
                    models.Index(fields=['expires_at', 'is_active'], name='customer_auth_guest_token_expires_active_idx'),
                    models.Index(fields=['created_at'], name='customer_auth_guest_token_created_idx'),
                ],
            },
        ),
    ]
