# Generated by refactoring: move preference fields to user_preferences.UserPreference

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='preferred_radius_m',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='preferred_categories',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='last_known_lat',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='last_known_lng',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='notification_enabled',
        ),
        migrations.RemoveIndex(
            model_name='customeruser',
            name='customer_auth_customer_user_location_idx',
        ),
    ]
