# Generated by Django 4.2.16 on 2026-02-25 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0006_discount_voicebotconfig_vendor_activation_stage_and_more"),
        ("governance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blacklist",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="False = entry has been lifted via appeal process.",
            ),
        ),
        migrations.AlterField(
            model_name="blacklist",
            name="reason",
            field=models.TextField(
                help_text="Mandatory reason for blacklisting (audit trail per spec §6.3)."
            ),
        ),
        migrations.AlterField(
            model_name="blacklist",
            name="value",
            field=models.CharField(
                db_index=True,
                help_text="Blacklisted value: phone number, device ID, or 'lat,lon' string.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="granted",
            field=models.BooleanField(help_text="True = opted in, False = opted out."),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP address at time of consent action.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="fraudscore",
            name="actor_email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                help_text="Denormalised email of the entity being scored.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="fraudscore",
            name="is_auto_suspended",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True if score crossed AUTO_SUSPEND_THRESHOLD (6+).",
            ),
        ),
        migrations.AlterField(
            model_name="fraudscore",
            name="signals",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ordered list of signal events: [{signal, score_delta, reason, ts}].",
            ),
        ),
        migrations.AlterField(
            model_name="fraudscore",
            name="vendor",
            field=models.OneToOneField(
                blank=True,
                help_text="Vendor this score belongs to. Null for user-level scores.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fraud_score",
                to="vendors.vendor",
            ),
        ),
        migrations.AlterField(
            model_name="vendorsuspension",
            name="appeal_notes",
            field=models.TextField(
                blank=True, help_text="Notes from the appeal review (Ops Manager)."
            ),
        ),
        migrations.AlterField(
            model_name="vendorsuspension",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="False = action lifted (appeal approved or temporary suspension expired).",
            ),
        ),
        migrations.AlterField(
            model_name="vendorsuspension",
            name="policy_reference",
            field=models.CharField(
                blank=True,
                help_text="Optional policy clause reference, e.g. 'Section 4.3 — Fake Promotions'.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="vendorsuspension",
            name="reason",
            field=models.TextField(
                help_text="Mandatory reason for the enforcement action (shown to vendor)."
            ),
        ),
        migrations.AlterField(
            model_name="vendorsuspension",
            name="suspension_ends_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="For TEMPORARY_SUSPENSION only — when the suspension expires.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vendortosacceptance",
            name="accepted_by_email",
            field=models.EmailField(
                help_text="Email of the person who accepted the ToS (denormalised for audit).",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="vendortosacceptance",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP address at time of acceptance.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="vendortosacceptance",
            name="tos_version",
            field=models.CharField(
                default="1.0",
                help_text="Version of the Terms of Service accepted.",
                max_length=20,
            ),
        ),
    ]
