# Generated by Django 4.2.16 on 2026-02-25 22:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique slug for programmatic lookup, e.g. 'claim_approved'.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "title_template",
                    models.CharField(
                        help_text="Title with {placeholder} variables.", max_length=500
                    ),
                ),
                (
                    "body_template",
                    models.TextField(help_text="Body with {placeholder} variables."),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("CLAIM_STATUS", "Claim Status"),
                            ("SUBSCRIPTION", "Subscription"),
                            ("PROMOTION", "Promotion"),
                            ("SYSTEM", "System"),
                            ("CHURN_PREVENTION", "Churn Prevention"),
                            ("MODERATION", "Moderation"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[("VENDOR", "Vendor"), ("CUSTOMER", "Customer")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "recipient_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="UUID of the recipient (CustomerUser.id or Vendor.owner.id).",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("body", models.TextField()),
                (
                    "data_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra JSON payload for push notification data field.",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("PUSH", "Push"), ("EMAIL", "Email"), ("SMS", "SMS")],
                        db_index=True,
                        max_length=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details on delivery failure."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="notifications.notificationtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_type", "recipient_id"],
                        name="notif_recipient_idx",
                    ),
                    models.Index(
                        fields=["status", "channel"], name="notif_status_channel_idx"
                    ),
                ],
            },
        ),
    ]
