# Generated by Django 4.2.16 on 2026-02-25 21:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendors", "0006_discount_voicebotconfig_vendor_activation_stage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        db_index=True,
                        help_text="Stripe Subscription ID (sub_xxx).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Price ID for the current plan.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAST_DUE", "Past Due"),
                            ("CANCELED", "Canceled"),
                            ("INCOMPLETE", "Incomplete"),
                            ("TRIALING", "Trialing"),
                            ("UNPAID", "Unpaid"),
                        ],
                        db_index=True,
                        default="INCOMPLETE",
                        max_length=20,
                    ),
                ),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_subscription",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Subscription",
                "verbose_name_plural": "Vendor Subscriptions",
            },
        ),
        migrations.CreateModel(
            name="StripeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_event_id",
                    models.CharField(
                        db_index=True,
                        help_text="Stripe Event ID (evt_xxx) — idempotency key.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="Stripe event type (e.g. checkout.session.completed).",
                        max_length=100,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict, help_text="Full Stripe event payload."
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if event was successfully processed.",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if processing failed."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Stripe Event",
                "verbose_name_plural": "Stripe Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "processed"],
                        name="stripe_evt_type_proc_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StripeCustomer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        db_index=True,
                        help_text="Stripe Customer ID (cus_xxx).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_customer",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stripe Customer",
                "verbose_name_plural": "Stripe Customers",
            },
        ),
    ]
