# Generated by Django 4.2.16 on 2026-02-25 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_subscriptionpackage_analytics_level_and_more"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorsubscription",
            name="package",
            field=models.ForeignKey(
                blank=True,
                help_text="FK to SubscriptionPackage for the current tier.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendor_subscriptions",
                to="subscriptions.subscriptionpackage",
            ),
        ),
        migrations.AddField(
            model_name="vendorsubscription",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stripe Customer ID (cus_xxx) — denormalised for quick lookup.",
                max_length=255,
            ),
        ),
    ]
