# Generated by Django 4.2.7 on 2026-02-28 12:00

import django.db.models.deletion
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_view', models.CharField(choices=[('AR', 'AR View'), ('MAP', 'Map View'), ('LIST', 'List View')], default='AR', max_length=10)),
                ('search_radius_m', models.IntegerField(db_index=True, default=500)),
                ('show_open_now_only', models.BooleanField(default=False)),
                ('preferred_category_slugs', models.JSONField(blank=True, default=list)),
                ('price_range', models.CharField(choices=[('BUDGET', 'Budget'), ('MID', 'Mid Range'), ('PREMIUM', 'Premium')], default='MID', max_length=10)),
                ('theme', models.CharField(choices=[('DARK', 'Dark'), ('LIGHT', 'Light'), ('SYSTEM', 'System')], default='DARK', max_length=10)),
                ('notifications_nearby_deals', models.BooleanField(default=True)),
                ('notifications_flash_deals', models.BooleanField(default=True)),
                ('notifications_new_vendors', models.BooleanField(default=True)),
                ('notifications_all_off', models.BooleanField(default=False)),
                ('auto_location_enabled', models.BooleanField(default=True)),
                ('manual_location_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('manual_location_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('manual_location_name', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest_token', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_auth.customeruser')),
            ],
            options={
                'db_table': 'user_preferences',
                'indexes': [
                    models.Index(fields=['user'], name='user_preferences_user_idx'),
                    models.Index(fields=['guest_token'], name='user_preferences_guest_token_idx'),
                    models.Index(fields=['default_view'], name='user_preferences_default_view_idx'),
                    models.Index(fields=['search_radius_m'], name='user_preferences_search_radius_idx'),
                    models.Index(fields=['updated_at'], name='user_preferences_updated_idx'),
                ],
                'unique_together': {('user',), ('guest_token',)},
            },
        ),
        migrations.CreateModel(
            name='UserSearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(db_index=True, max_length=200)),
                ('query_type', models.CharField(choices=[('TEXT', 'Text Search'), ('VOICE', 'Voice Search'), ('TAG', 'Tag Browse')], db_index=True, max_length=10)),
                ('extracted_category', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('extracted_intent', models.CharField(blank=True, max_length=50, null=True)),
                ('extracted_price_range', models.CharField(blank=True, max_length=10, null=True)),
                ('search_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('search_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('search_radius_m', models.IntegerField(blank=True, null=True)),
                ('result_count', models.IntegerField(default=0)),
                ('navigated_to_vendor_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('searched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guest_token', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_auth.customeruser')),
            ],
            options={
                'db_table': 'user_search_history',
                'indexes': [
                    models.Index(fields=['user', 'searched_at'], name='user_preferences_search_user_date_idx'),
                    models.Index(fields=['guest_token', 'searched_at'], name='user_preferences_search_guest_date_idx'),
                    models.Index(fields=['query_type', 'searched_at'], name='user_preferences_search_type_date_idx'),
                    models.Index(fields=['extracted_category', 'searched_at'], name='user_preferences_search_category_date_idx'),
                    models.Index(fields=['navigated_to_vendor_id'], name='user_preferences_search_vendor_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='UserVendorInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.UUIDField(db_index=True)),
                ('interaction_type', models.CharField(choices=[('VIEW', 'Profile View'), ('TAP', 'AR Marker Tap'), ('NAVIGATION', 'Navigation Click'), ('CALL', 'Phone Call'), ('REEL_VIEW', 'Reel View'), ('PROMOTION_TAP', 'Promotion Tap'), ('ARRIVAL', 'Physical Arrival'), ('SHARE', 'Share Vendor'), ('FAVORITE', 'Add to Favorites')], db_index=True, max_length=20)),
                ('session_id', models.UUIDField(db_index=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('interacted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guest_token', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_auth.customeruser')),
            ],
            options={
                'db_table': 'user_vendor_interactions',
                'indexes': [
                    models.Index(fields=['vendor_id', 'interaction_type', 'interacted_at'], name='user_preferences_interaction_vendor_type_date_idx'),
                    models.Index(fields=['user', 'interacted_at'], name='user_preferences_interaction_user_date_idx'),
                    models.Index(fields=['guest_token', 'interacted_at'], name='user_preferences_interaction_guest_date_idx'),
                    models.Index(fields=['session_id', 'interacted_at'], name='user_preferences_interaction_session_date_idx'),
                    models.Index(fields=['interacted_at'], name='user_preferences_interaction_date_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='FlashDealAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_id', models.UUIDField(db_index=True)),
                ('vendor_id', models.UUIDField(db_index=True)),
                ('alerted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dismissed', models.BooleanField(db_index=True, default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('tapped', models.BooleanField(db_index=True, default=False)),
                ('tapped_at', models.DateTimeField(blank=True, null=True)),
                ('guest_token', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_auth.customeruser')),
            ],
            options={
                'db_table': 'flash_deal_alerts',
                'indexes': [
                    models.Index(fields=['user', 'discount_id'], name='user_preferences_flash_alert_user_discount_idx'),
                    models.Index(fields=['guest_token', 'discount_id'], name='user_preferences_flash_alert_guest_discount_idx'),
                    models.Index(fields=['alerted_at'], name='user_preferences_flash_alert_date_idx'),
                    models.Index(fields=['dismissed', 'alerted_at'], name='user_preferences_flash_alert_dismissed_date_idx'),
                ],
                'unique_together': {('user', 'discount_id'), ('guest_token', 'discount_id')},
            },
        ),
        migrations.CreateModel(
            name='NearbyReelView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reel_id', models.UUIDField(db_index=True)),
                ('vendor_id', models.UUIDField(db_index=True)),
                ('watched_seconds', models.IntegerField(default=0)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('cta_tapped', models.BooleanField(db_index=True, default=False)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guest_token', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_auth.customeruser')),
            ],
            options={
                'db_table': 'nearby_reel_views',
                'indexes': [
                    models.Index(fields=['reel_id', 'viewed_at'], name='user_preferences_reel_view_reel_date_idx'),
                    models.Index(fields=['vendor_id', 'viewed_at'], name='user_preferences_reel_view_vendor_date_idx'),
                    models.Index(fields=['user', 'viewed_at'], name='user_preferences_reel_view_user_date_idx'),
                    models.Index(fields=['guest_token', 'viewed_at'], name='user_preferences_reel_view_guest_date_idx'),
                    models.Index(fields=['completed', 'viewed_at'], name='user_preferences_reel_view_completed_date_idx'),
                    models.Index(fields=['cta_tapped', 'viewed_at'], name='user_preferences_reel_view_cta_date_idx'),
                ],
            },
        ),
    ]
