# Generated by Django 4.2.16 on 2026-02-25 21:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customeruser_otprequest_alter_adminuser_managers_and_more"),
        ("vendors", "0005_gps_baseline_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage Off"),
                            ("FIXED_AMOUNT", "Fixed Amount Off"),
                            ("BUY_ONE_GET_ONE", "Buy One Get One"),
                            ("HAPPY_HOUR", "Happy Hour"),
                            ("FLASH_DEAL", "Flash Deal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (e.g. 20.00) or fixed amount in PKR.",
                        max_digits=10,
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        default="ALL",
                        help_text="What the discount applies to: ALL, DINE_IN, DELIVERY, PICKUP, SPECIFIC_ITEM.",
                        max_length=50,
                    ),
                ),
                (
                    "item_description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of specific items the discount applies to.",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(help_text="When the discount becomes active."),
                ),
                (
                    "end_time",
                    models.DateTimeField(help_text="When the discount expires."),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the discount repeats on specified days.",
                    ),
                ),
                (
                    "recurrence_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="ISO day numbers (1=MON..7=SUN) for recurring discounts.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Managed by discount_scheduler Celery task — not by API consumer.",
                    ),
                ),
                (
                    "min_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum order value for the discount to apply (PKR).",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Discount",
                "verbose_name_plural": "Discounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoiceBotConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "menu_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of menu item dicts: [{name, price, description, is_available}].",
                    ),
                ),
                (
                    "opening_hours_summary",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable summary of business hours for voice responses.",
                    ),
                ),
                (
                    "delivery_info",
                    models.TextField(
                        blank=True,
                        help_text="Delivery/pickup information for voice responses.",
                    ),
                ),
                (
                    "discount_summary",
                    models.TextField(
                        blank=True,
                        help_text="Auto-updated summary of active discounts for voice responses.",
                    ),
                ),
                (
                    "custom_qa_pairs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of custom QA dicts: [{question, answer}].",
                    ),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the vendor last updated their voice bot data.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Voice Bot Config",
                "verbose_name_plural": "Voice Bot Configs",
            },
        ),
        migrations.AddField(
            model_name="vendor",
            name="activation_stage",
            field=models.CharField(
                choices=[
                    ("CLAIM", "Claim"),
                    ("ENGAGEMENT", "Engagement"),
                    ("MONETIZATION", "Monetization"),
                    ("GROWTH", "Growth"),
                    ("RETENTION", "Retention"),
                ],
                db_index=True,
                default="CLAIM",
                help_text="Current stage in the Progressive Activation Strategy.",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="claimed_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when claim was approved.", null=True
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="cover_photo_key",
            field=models.CharField(
                blank=True,
                help_text="S3 object key for vendor cover photo.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="is_verified",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Admin-verified vendor (badge in UI).",
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="location_pending_review",
            field=models.BooleanField(
                default=False,
                help_text="True when vendor has submitted a location change awaiting admin approval.",
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="logo_key",
            field=models.CharField(
                blank=True, help_text="S3 object key for vendor logo.", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="offers_delivery",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendor",
            name="offers_pickup",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendor",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Customer who has claimed ownership of this vendor. Phase B.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_vendors",
                to="accounts.customeruser",
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="subscription_level",
            field=models.CharField(
                choices=[
                    ("SILVER", "Silver"),
                    ("GOLD", "Gold"),
                    ("DIAMOND", "Diamond"),
                    ("PLATINUM", "Platinum"),
                ],
                db_index=True,
                default="SILVER",
                help_text="Current subscription tier. Defaults to SILVER (free).",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="subscription_valid_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Subscription expiry date. Null means no active paid subscription.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="total_profile_taps",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Lifetime profile tap count — updated by analytics tasks.",
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="total_views",
            field=models.PositiveIntegerField(
                default=0, help_text="Lifetime view count — updated by analytics tasks."
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="claimed_status",
            field=models.CharField(
                choices=[
                    ("UNCLAIMED", "Unclaimed"),
                    ("CLAIM_PENDING", "Claim Pending"),
                    ("CLAIMED", "Claimed"),
                    ("CLAIM_REJECTED", "Claim Rejected"),
                ],
                db_index=True,
                default="UNCLAIMED",
                help_text="Claim lifecycle: UNCLAIMED → CLAIM_PENDING → CLAIMED/CLAIM_REJECTED.",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["subscription_level", "is_deleted"],
                name="vendor_sub_deleted_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["is_verified", "is_deleted"], name="vendor_verified_deleted_idx"
            ),
        ),
        migrations.AddField(
            model_name="voicebotconfig",
            name="vendor",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voice_bot_config",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                to="vendors.vendor",
            ),
        ),
        migrations.AddIndex(
            model_name="discount",
            index=models.Index(
                fields=["vendor", "is_active"], name="discount_vendor_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discount",
            index=models.Index(
                fields=["start_time", "end_time"], name="discount_time_range_idx"
            ),
        ),
    ]
