# Generated by Django 4.2.16 on 2026-02-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0006_discount_voicebotconfig_vendor_activation_stage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="ar_badge_text",
            field=models.CharField(
                blank=True,
                help_text="Short badge text for AR overlay, e.g. '20% OFF', 'Happy Hour'.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="delivery_radius_m",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Delivery radius in metres for free-delivery campaigns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="free_delivery_distance_m",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Distance in metres within which delivery is free.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="navigation_clicks_during_campaign",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Navigation click count during this campaign — updated by analytics tasks.",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="taps_during_campaign",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Tap count during this campaign — updated by analytics tasks.",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="views_during_campaign",
            field=models.PositiveIntegerField(
                default=0,
                help_text="View count during this campaign — updated by analytics tasks.",
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="activation_stage_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of last activation stage transition.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="total_navigation_clicks",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Lifetime navigation click count — updated by analytics tasks.",
            ),
        ),
        migrations.AddField(
            model_name="voicebotconfig",
            name="completeness_score",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Auto-calculated 0-100 score of voice bot data completeness.",
            ),
        ),
        migrations.AddField(
            model_name="voicebotconfig",
            name="intro_message",
            field=models.TextField(
                blank=True, help_text="Custom greeting/intro message for the voice bot."
            ),
        ),
        migrations.AddField(
            model_name="voicebotconfig",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether the voice bot is enabled for this vendor.",
            ),
        ),
        migrations.AddField(
            model_name="voicebotconfig",
            name="pickup_available",
            field=models.BooleanField(
                default=False,
                help_text="Whether this vendor offers pickup — used in voice responses.",
            ),
        ),
    ]
