# Generated by Django 4.2.16 on 2026-02-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0007_discount_ar_badge_text_discount_delivery_radius_m_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("PERCENTAGE", "Percentage Off"),
                    ("FIXED_AMOUNT", "Fixed Amount Off"),
                    ("BUY_ONE_GET_ONE", "Buy One Get One"),
                    ("HAPPY_HOUR", "Happy Hour"),
                    ("FLASH_DEAL", "Flash Deal"),
                    ("ITEM_SPECIFIC", "Item Specific"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="voicebotconfig",
            name="delivery_info",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Delivery info dict: {radius_km, free_within_km, charges}.",
            ),
        ),
    ]
