# Generated by Django 4.2.16 on 2026-02-25 21:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_adminuser_governance_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of phone number for unique lookups without decryption.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "phone_encrypted",
                    models.BinaryField(
                        help_text="AES-256-GCM encrypted phone number. Decrypt in services.py only."
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("CUSTOMER", "Customer"), ("VENDOR", "Vendor")],
                        db_index=True,
                        default="CUSTOMER",
                        max_length=10,
                    ),
                ),
                (
                    "device_token",
                    models.CharField(
                        blank=True,
                        help_text="FCM/APNS push notification token.",
                        max_length=500,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "is_phone_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Set True after first successful OTP verification.",
                    ),
                ),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer User",
                "verbose_name_plural": "Customer Users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OTPRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of phone number.",
                        max_length=64,
                    ),
                ),
                (
                    "otp_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the OTP code — never store plaintext.",
                        max_length=64,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("CLAIM_VERIFY", "Claim Verify"),
                            ("EMAIL_VERIFY", "Email Verify"),
                        ],
                        default="LOGIN",
                        max_length=20,
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of verify attempts. Max 3 before OTP is invalidated.",
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="OTP expires 5 minutes after creation."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "OTP Request",
                "verbose_name_plural": "OTP Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelManagers(
            name="adminuser",
            managers=[],
        ),
        migrations.RenameIndex(
            model_name="adminuser",
            new_name="accounts_ad_role_01c316_idx",
            old_name="accounts_ad_role_is_a_idx",
        ),
        migrations.AddIndex(
            model_name="otprequest",
            index=models.Index(
                fields=["phone_hash", "is_used", "expires_at"],
                name="accounts_ot_phone_h_c314c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customeruser",
            index=models.Index(
                fields=["user_type", "is_active"], name="accounts_cu_user_ty_f22747_idx"
            ),
        ),
    ]
