# Generated by Django 4.2.16 on 2026-02-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customeruser_otprequest_alter_adminuser_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeruser",
            name="last_known_lat",
            field=models.FloatField(
                blank=True,
                help_text="Last known latitude — updated on each discovery request.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customeruser",
            name="last_known_lng",
            field=models.FloatField(
                blank=True,
                help_text="Last known longitude — updated on each discovery request.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customeruser",
            name="preferred_categories",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of preferred category tag slugs for personalised results.",
            ),
        ),
        migrations.AddField(
            model_name="customeruser",
            name="preferred_radius",
            field=models.PositiveIntegerField(
                default=500,
                help_text="Default search radius in meters for nearby discovery.",
            ),
        ),
    ]
