# Generated by Django 4.2.16 on 2026-02-25 21:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriptionPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("SILVER", "Silver"),
                            ("GOLD", "Gold"),
                            ("DIAMOND", "Diamond"),
                            ("PLATINUM", "Platinum"),
                        ],
                        db_index=True,
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly price in PKR.",
                        max_digits=10,
                    ),
                ),
                (
                    "max_videos",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum reel/video uploads. Silver=1, Gold=3, Diamond=6, Platinum=unlimited(999).",
                    ),
                ),
                (
                    "daily_happy_hours_allowed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Max happy hours per day. Silver=0, Gold=1, Diamond=3, Platinum=unlimited(99).",
                    ),
                ),
                (
                    "has_voice_bot",
                    models.BooleanField(
                        default=False,
                        help_text="Silver=False, Gold=True(basic), Diamond=True(dynamic), Platinum=True(advanced).",
                    ),
                ),
                (
                    "has_predictive_reports",
                    models.BooleanField(default=False, help_text="Platinum only."),
                ),
                (
                    "sponsored_placement_level",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("LIMITED_TIME", "Limited Time"),
                            ("AREA_BOOST", "Area Boost"),
                            ("AREA_EXCLUSIVE", "Area Exclusive"),
                        ],
                        default="NONE",
                        help_text="Silver=NONE, Gold=LIMITED_TIME, Diamond=AREA_BOOST, Platinum=AREA_EXCLUSIVE.",
                        max_length=20,
                    ),
                ),
                (
                    "campaign_scheduling_level",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("BASIC", "Basic"),
                            ("ADVANCED", "Advanced"),
                            ("SMART_AUTOMATION", "Smart Automation"),
                        ],
                        default="NONE",
                        help_text="Silver=NONE, Gold=BASIC, Diamond=ADVANCED, Platinum=SMART_AUTOMATION.",
                        max_length=20,
                    ),
                ),
                (
                    "voice_search_priority",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGHEST", "Highest"),
                        ],
                        default="NONE",
                        help_text="Silver=NONE, Gold=LOW, Diamond=MEDIUM, Platinum=HIGHEST.",
                        max_length=10,
                    ),
                ),
                (
                    "visibility_boost_weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Ranking multiplier. Silver=1.0, Gold=1.2, Diamond=1.5, Platinum=2.0.",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription Package",
                "verbose_name_plural": "Subscription Packages",
                "ordering": ["price_monthly"],
            },
        ),
    ]
