# Generated by Django 4.2.16 on 2026-02-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpackage",
            name="analytics_level",
            field=models.CharField(
                choices=[
                    ("BASIC", "Basic"),
                    ("STANDARD", "Standard"),
                    ("ADVANCED", "Advanced"),
                    ("PREDICTIVE", "Predictive"),
                ],
                default="BASIC",
                help_text="Silver=BASIC, Gold=STANDARD, Diamond=ADVANCED, Platinum=PREDICTIVE.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpackage",
            name="badge_type",
            field=models.CharField(
                choices=[
                    ("CLAIMED", "Claimed"),
                    ("VERIFIED", "Verified"),
                    ("PREMIUM", "Premium"),
                    ("ELITE", "Elite"),
                ],
                default="CLAIMED",
                help_text="Silver=CLAIMED, Gold=VERIFIED, Diamond=PREMIUM, Platinum=ELITE.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpackage",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0, help_text="UI display order. Lower number = shown first."
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpackage",
            name="max_delivery_configs",
            field=models.IntegerField(
                default=0,
                help_text="Max delivery configurations. 0=none, -1=unlimited. Silver=0, Gold=1, Diamond=3, Platinum=-1.",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpackage",
            name="price_monthly_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly price in USD (for Stripe checkout). Null for free tier.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpackage",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Price ID for this tier (e.g. price_xxx). Blank for free tier.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpackage",
            name="support_level",
            field=models.CharField(
                choices=[
                    ("COMMUNITY", "Community"),
                    ("EMAIL_48H", "Email 48h"),
                    ("PRIORITY_24H", "Priority 24h"),
                    ("DEDICATED", "Dedicated"),
                ],
                default="COMMUNITY",
                help_text="Silver=COMMUNITY, Gold=EMAIL_48H, Diamond=PRIORITY_24H, Platinum=DEDICATED.",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpackage",
            name="voice_bot_type",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("BASIC", "Basic"),
                    ("DYNAMIC", "Dynamic"),
                    ("ADVANCED", "Advanced"),
                ],
                default="NONE",
                help_text="Silver=NONE, Gold=BASIC, Diamond=DYNAMIC, Platinum=ADVANCED.",
                max_length=10,
            ),
        ),
    ]
